Header header

string qc_type
float32 qc_collect_time

string qc_status

int32 num_peaks
float32[] peak_locations
float32[] peak_heights

int32 peak_channel
int32 peak_channel_bound_low
int32 peak_channel_bound_high
bool peak_channel_in_bounds

float32 peak_cps
float32 peak_cps_bound_low
float32 peak_cps_bound_high
bool peak_cps_in_bounds

float32 fwhm
float32 fwhm_bound_low
float32 fwhm_bound_high
bool fwhm_in_bounds
